export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Footer } from './footer'
export { default as Header } from './header'
export { default as Portfolio } from './portfolio-display'
export { default as PortfolioItem } from './portfolio-item'
export { default as AboutCopy } from './about-copy'
