export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as Portfolio } from './portfolio'
export { default as Contact } from './contact'
export { default as About } from './about'
